<?php

namespace Database\Seeders;

use App\Models\Module;
use Illuminate\Database\Seeder;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $modules = [
            [
                'vc_nome' => 'Fontes',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'fonte',
               // 'vc_group_menu' => 'Gestão de modelos',
                'vc_url' => '/admin/fonte/index',
                'vc_icon' => 'database-line',
                'it_id_group' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Categorias de Modelo',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'categoria_modelo',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/categoria_modelo/index',
                'vc_icon' => 'folder-line',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Pre de Processamentos',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'pre_processamento',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/pre_processamento/index',
                'vc_icon' => 'filter-line',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Metricas',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'metrica',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/metrica/index',
                'vc_icon' => 'bar-chart-line',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Hiperparametros de Categoria de Modelo',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'hiperparametro_categoria_modelo',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/hiperparametro_categoria_modelo/index',
                'vc_icon' => 'settings-line',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Datasets',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'dataset',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/dataset/index',
                'vc_icon' => 'file-text-line',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Treinamentos',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'treinamento',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/treinamento/index',
                'vc_icon' => 'play-circle-line',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Treinamento de Pre de Processamentos',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'treinamento_pre_processamento',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/treinamento_pre_processamento/index',
                'vc_icon' => 'link',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Treinamento de Metricas',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'treinamento_metrica',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/treinamento_metrica/index',
                'vc_icon' => 'link',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Modelos',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'modelo',
               // 'vc_group_menu' => 'Gestão de modelos',
                'vc_url' => '/admin/modelo/index',
                'vc_icon' => 'cube-line',
                'it_id_group' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Hiperparametros de Modelo',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'hiperparametro_modelo',
               // 'vc_group_menu' => 'Outros',
                'vc_url' => '/admin/hiperparametro_modelo/index',
                'vc_icon' => 'settings-line',
                'it_id_group' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Roles',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'role',
               // 'vc_group_menu' => 'Usuários e Autenticação',
                'vc_url' => '/admin/role/index',
                'vc_icon' => 'lock-2-line',
                'it_id_group' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Role de Permissions',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'role_permissions',
               // 'vc_group_menu' => 'Usuários e Autenticação',
                'vc_url' => '/admin/role_permissions/index',
                'vc_icon' => 'lock-2-line',
                'it_id_group' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Users',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'user',
               // 'vc_group_menu' => 'Usuários e Autenticação',
                'vc_url' => '/admin/user/index',
                'vc_icon' => 'user-line',
                'it_id_group' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vc_nome' => 'Logs',
                'vc_prefix' => 'admin',
                //'vc_route_group' => 'admin',
                'vc_route_subgroup' => 'log',
               // 'vc_group_menu' => 'Gestão de modelos',
                'vc_url' => '/admin/log/index',
                'vc_icon' => 'history-line',
                'it_id_group' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($modules as $module) {
            Module::create($module);
        }
    }
}